[package]
name = "raymarching_voxels"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.34.0"
winit = "0.29.15"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"